services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - psgdata:/var/lib/postgresql/data
volumes:
    psgdata:
        